import React, { useCallback, useEffect, useRef, useState } from "react";
import {
  Alert,
  Modal,
  Pressable,
  ScrollView,
  Share,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";

import { radii, spacing, typography } from "@/src/theme/tokens";
import { TranscriptParagraphText } from "@/src/components/TranscriptParagraphText";
import { useTheme } from "@/src/theme/ThemeProvider";
import { api, NoteCollection } from "@/src/api/client";
import { UserNote } from "@/src/utils/userStore";
import { useToast } from "@/src/toast/ToastContext";

// ─────────────────────────────────────────────────────────────
// Export Service
// Designed as a standalone module for future DOCX/Markdown/Print support.
// ─────────────────────────────────────────────────────────────
function buildTextExport(collection: NoteCollection, notes: UserNote[]): string {
  const createdDate = new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });
  const sep = "─".repeat(40);
  const lines: string[] = [collection.title, "", `Created: ${createdDate}`, "", sep, ""];

  notes.forEach((note, idx) => {
    const meta = [note.date_code, note.speaker, note.language].filter(Boolean).join(" · ");
    lines.push(note.testimony_title || "Sermon");
    if (meta) lines.push(meta);
    lines.push("", `Paragraph ${note.paragraph_number}`, "", `"${note.text}"`, "");
    if (note.personal_note?.trim()) {
      lines.push("My Notes:", note.personal_note.trim(), "");
    }
    if (idx < notes.length - 1) { lines.push(sep, ""); }
  });

  lines.push("", sep, "Generated by Golden Nuggets");
  return lines.join("\n");
}

function buildHtmlExport(collection: NoteCollection, notes: UserNote[]): string {
  const createdDate = new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" });
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

  const passagesHtml = notes.map((note) => {
    const meta = [note.date_code, note.speaker, note.language].filter(Boolean).join(" · ");
    const personalNote = note.personal_note?.trim()
      ? `<div class="my-notes-label">My Notes</div><p class="personal-note">${esc(note.personal_note.trim())}</p>`
      : "";
    return `<div class="passage">
      <div class="sermon-title">${esc(note.testimony_title || "Sermon")}</div>
      ${meta ? `<div class="sermon-meta">${esc(meta)}</div>` : ""}
      <div class="para-num">Paragraph ${note.paragraph_number}</div>
      <blockquote class="quote">${esc(note.text)}</blockquote>
      ${personalNote}
    </div>`;
  }).join("<hr/>");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>${esc(collection.title)}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,400;0,700;1,400&family=Inter:wght@400;600&display=swap');
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Inter',sans-serif;font-size:14px;line-height:1.7;color:#1a1f1e;max-width:720px;margin:0 auto;padding:48px 32px}
    h1{font-family:'Merriweather',serif;font-size:28px;margin-bottom:6px}
    .created{color:#6b7280;font-size:13px;margin-bottom:40px}
    hr{border:none;border-top:1px solid #e5e7eb;margin:36px 0}
    .passage{page-break-inside:avoid}
    .sermon-title{font-weight:600;font-size:15px;margin-bottom:2px}
    .sermon-meta{color:#6b7280;font-size:12px;margin-bottom:12px}
    .para-num{font-size:11px;font-weight:600;color:#10b981;letter-spacing:1px;text-transform:uppercase;margin-bottom:8px}
    blockquote.quote{font-family:'Merriweather',serif;font-style:italic;font-size:15px;line-height:1.8;color:#1a1f1e;border-left:3px solid #10b981;padding-left:16px;margin:0 0 16px 0}
    .my-notes-label{font-size:10px;font-weight:600;color:#9ca3af;letter-spacing:1.2px;text-transform:uppercase;margin-bottom:4px}
    .personal-note{font-size:13px;color:#374151;line-height:1.7}
    .footer{margin-top:48px;border-top:1px solid #e5e7eb;padding-top:16px;font-size:11px;color:#9ca3af;text-align:center}
    @media print{body{padding:0;font-size:13px}h1{font-size:22px}}
  </style>
</head>
<body>
  <h1>${esc(collection.title)}</h1>
  <div class="created">Created: ${esc(createdDate)}</div>
  ${passagesHtml}
  <div class="footer">Generated by Golden Nuggets</div>
</body>
</html>`;
}

async function exportAsText(collection: NoteCollection, notes: UserNote[]) {
  await Share.share({ message: buildTextExport(collection, notes), title: collection.title });
}

async function saveAsTxt(collection: NoteCollection, notes: UserNote[], onError: (m: string) => void) {
  const safeTitle = collection.title.replace(/[^a-zA-Z0-9_\- ]/g, "").trim() || "collection";
  const path = `${FileSystem.documentDirectory}${safeTitle}.txt`;
  await FileSystem.writeAsStringAsync(path, buildTextExport(collection, notes), {
    encoding: FileSystem.EncodingType.UTF8,
  });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(path, { mimeType: "text/plain", dialogTitle: `Save "${collection.title}"` });
  } else {
    onError("Sharing is not available on this device.");
  }
}

async function saveAsPdf(collection: NoteCollection, notes: UserNote[], onError: (m: string) => void) {
  const safeTitle = collection.title.replace(/[^a-zA-Z0-9_\- ]/g, "").trim() || "collection";
  const path = `${FileSystem.documentDirectory}${safeTitle}.html`;
  await FileSystem.writeAsStringAsync(path, buildHtmlExport(collection, notes), {
    encoding: FileSystem.EncodingType.UTF8,
  });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(path, {
      mimeType: "text/html",
      dialogTitle: `Export "${collection.title}"`,
      UTI: "public.html",
    });
  } else {
    onError("Sharing is not available on this device.");
  }
}

// ─────────────────────────────────────────────────────────────
// Export Bottom Sheet
// ─────────────────────────────────────────────────────────────
function ExportSheet({
  visible, collection, notes, onClose, toast, colors, theme,
}: {
  visible: boolean;
  collection: NoteCollection;
  notes: UserNote[];
  onClose: () => void;
  toast: { show: (msg: string, type: "info" | "success" | "error") => void };
  colors: any;
  theme: string;
}) {
  const insets = useSafeAreaInsets();
  const [busy, setBusy] = useState(false);

  const run = async (fn: () => Promise<void>) => {
    if (busy) return;
    setBusy(true);
    try { await fn(); onClose(); }
    catch (e: any) { toast.show(e?.message || "Export failed", "error"); }
    finally { setBusy(false); }
  };

  if (!visible) return null;

  const bg = theme === "dark" ? colors.surface : "#fff";
  const iconWrap = {
    width: 40, height: 40, borderRadius: 12,
    backgroundColor: colors.emeraldSoft || "rgba(16,185,129,0.12)",
    alignItems: "center" as const, justifyContent: "center" as const,
  };
  const option = { flexDirection: "row" as const, alignItems: "center" as const, gap: spacing[3], paddingVertical: spacing[3] };

  return (
    <Modal transparent animationType="slide" visible={visible} onRequestClose={onClose}>
      <Pressable style={{ flex: 1, backgroundColor: "rgba(0,0,0,0.55)", justifyContent: "flex-end" }} onPress={onClose}>
        <Pressable
          onPress={(e) => e.stopPropagation()}
          style={{
            backgroundColor: bg,
            borderTopLeftRadius: radii["3xl"], borderTopRightRadius: radii["3xl"],
            paddingTop: spacing[2], paddingBottom: insets.bottom + spacing[6],
            paddingHorizontal: spacing[5], borderWidth: 1, borderBottomWidth: 0, borderColor: colors.hairline,
          }}
        >
          <View style={{ width: 40, height: 4, borderRadius: 2, backgroundColor: colors.white10 || "#e5e7eb", alignSelf: "center", marginBottom: spacing[5] }} />

          <Text style={{ fontSize: 16, fontFamily: typography.serif, color: colors.foreground, marginBottom: spacing[5], textAlign: "center" }}>
            Export Notes
          </Text>

          {/* Share as Text */}
          <Pressable onPress={() => run(() => exportAsText(collection, notes))} style={({ pressed }) => [option, pressed && { opacity: 0.7 }]}>
            <View style={iconWrap}><Ionicons name="share-outline" size={20} color={colors.emerald} /></View>
            <View style={{ flex: 1 }}>
              <Text style={{ fontFamily: typography.sansSemi, fontSize: 15, color: colors.foreground }}>Share as Text</Text>
              <Text style={{ fontFamily: typography.sans, fontSize: 12, color: colors.mutedForeground, marginTop: 2 }}>Send to Notes, Gmail, WhatsApp…</Text>
            </View>
          </Pressable>

          <View style={{ height: StyleSheet.hairlineWidth, backgroundColor: colors.hairline, marginVertical: spacing[2] }} />

          {/* Save as TXT */}
          <Pressable onPress={() => run(() => saveAsTxt(collection, notes, (m) => toast.show(m, "error")))} style={({ pressed }) => [option, pressed && { opacity: 0.7 }]}>
            <View style={iconWrap}><Ionicons name="document-text-outline" size={20} color={colors.emerald} /></View>
            <View style={{ flex: 1 }}>
              <Text style={{ fontFamily: typography.sansSemi, fontSize: 15, color: colors.foreground }}>Save to Device (.txt)</Text>
              <Text style={{ fontFamily: typography.sans, fontSize: 12, color: colors.mutedForeground, marginTop: 2 }}>Plain text — open in any text editor</Text>
            </View>
          </Pressable>

          <View style={{ height: StyleSheet.hairlineWidth, backgroundColor: colors.hairline, marginVertical: spacing[2] }} />

          {/* Save as PDF (HTML) */}
          <Pressable onPress={() => run(() => saveAsPdf(collection, notes, (m) => toast.show(m, "error")))} style={({ pressed }) => [option, pressed && { opacity: 0.7 }]}>
            <View style={iconWrap}><Ionicons name="print-outline" size={20} color={colors.emerald} /></View>
            <View style={{ flex: 1 }}>
              <Text style={{ fontFamily: typography.sansSemi, fontSize: 15, color: colors.foreground }}>Save to Device (.pdf)</Text>
              <Text style={{ fontFamily: typography.sans, fontSize: 12, color: colors.mutedForeground, marginTop: 2 }}>Print-ready HTML — open in Safari to save as PDF</Text>
            </View>
          </Pressable>

          <View style={{ height: StyleSheet.hairlineWidth, backgroundColor: colors.hairline, marginVertical: spacing[3] }} />

          <Pressable onPress={onClose} style={{ alignItems: "center", paddingVertical: spacing[2] }}>
            <Text style={{ fontFamily: typography.sansSemi, fontSize: 15, color: colors.mutedForeground }}>Cancel</Text>
          </Pressable>
        </Pressable>
      </Pressable>
    </Modal>
  );
}

// ─────────────────────────────────────────────────────────────
// Collection Screen
// ─────────────────────────────────────────────────────────────
export default function CollectionScreen() {
  const insets = useSafeAreaInsets();
  const params = useLocalSearchParams<{ id: string }>();
  const { colors, theme } = useTheme();
  const styles = getStyles(colors, theme);
  const toast = useToast();

  const [collection, setCollection] = useState<NoteCollection | null>(null);
  const [notes, setNotes] = useState<UserNote[]>([]);
  const [loading, setLoading] = useState(true);
  const [allCollections, setAllCollections] = useState<NoteCollection[]>([]);
  const [showExportSheet, setShowExportSheet] = useState(false);

  const load = useCallback(async () => {
    if (!params.id) return;
    setLoading(true);
    try {
      const [cols, nts] = await Promise.all([
        api.listCollections().catch(() => [] as NoteCollection[]),
        api.listNotes(params.id).catch(() => [] as UserNote[]),
      ]);
      setAllCollections(cols);
      setCollection(cols.find((c) => c.id === params.id) || null);
      setNotes(nts);
    } finally {
      setLoading(false);
    }
  }, [params.id]);

  useEffect(() => { load(); }, [load]);

  const handleRename = () => {
    if (!collection) return;
    Alert.prompt("Rename Collection", "Enter a new name:", async (title) => {
      if (!title?.trim()) return;
      const ok = await api.updateCollection(collection.id, { title: title.trim() });
      if (ok) {
        setCollection((prev) => prev ? { ...prev, title: title.trim() } : prev);
        toast.show("Collection renamed", "success");
      }
    }, "plain-text", collection.title);
  };

  const handleDelete = () => {
    if (!collection) return;
    const count = notes.length;
    Alert.alert(
      "Delete Collection",
      count > 0
        ? `"${collection.title}" contains ${count} passage${count === 1 ? "" : "s"}.\n\nThis will permanently delete all passages.`
        : `Delete "${collection.title}"?`,
      [
        { text: "Cancel", style: "cancel" },
        { text: "Delete", style: "destructive", onPress: async () => {
          await api.deleteCollection(collection.id);
          toast.show("Collection deleted", "info");
          router.back();
        }},
      ]
    );
  };

  if (loading) return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={22} color={colors.foreground} />
        </Pressable>
      </View>
      <Text style={styles.loadingText}>Loading…</Text>
    </View>
  );

  if (!collection) return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={22} color={colors.foreground} />
        </Pressable>
      </View>
      <Text style={styles.loadingText}>Collection not found.</Text>
    </View>
  );

  return (
    <View style={[styles.container, { paddingTop: insets.top }]}>
      {/* Header */}
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="chevron-back" size={22} color={colors.foreground} />
        </Pressable>
        <Text style={styles.headerTitle} numberOfLines={1}>{collection.title}</Text>
        <View style={{ flexDirection: "row", gap: spacing[1] }}>
          {notes.length > 0 && (
            <Pressable onPress={() => setShowExportSheet(true)} style={styles.headerBtn}>
              <Ionicons name="share-outline" size={19} color={colors.mutedForeground} />
            </Pressable>
          )}
          <Pressable onPress={handleRename} style={styles.headerBtn}>
            <Ionicons name="pencil-outline" size={18} color={colors.mutedForeground} />
          </Pressable>
          <Pressable onPress={handleDelete} style={styles.headerBtn}>
            <Ionicons name="trash-outline" size={18} color={colors.mutedForeground} />
          </Pressable>
        </View>
      </View>

      {/* Passage count */}
      <View style={styles.metaRow}>
        <Text style={styles.metaText}>{notes.length} {notes.length === 1 ? "passage" : "passages"}</Text>
      </View>

      {/* Passages */}
      {notes.length === 0 ? (
        <View style={styles.emptyWrap}>
          <Ionicons name="journal-outline" size={40} color={colors.mutedForeground} style={{ opacity: 0.3, marginBottom: spacing[4] }} />
          <Text style={styles.emptyTitle}>No passages yet</Text>
          <Text style={styles.emptyMessage}>Open a sermon and choose "Add To Notes".</Text>
        </View>
      ) : (
        <ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: spacing[5], paddingBottom: insets.bottom + spacing[10] }} showsVerticalScrollIndicator={false}>
          {notes.map((note) => (
            <PassageCard
              key={note.id}
              note={note}
              allCollections={allCollections.filter((c) => c.id !== collection.id)}
              colors={colors}
              theme={theme}
              onDelete={async (id) => {
                await api.deleteNote(id);
                setNotes((prev) => prev.filter((n) => n.id !== id));
                toast.show("Passage removed", "info");
              }}
              onMove={async (id, targetCollectionId) => {
                await api.moveNoteToCollection(id, targetCollectionId);
                setNotes((prev) => prev.filter((n) => n.id !== id));
                const targetCol = allCollections.find((c) => c.id === targetCollectionId);
                toast.show(`Moved to "${targetCol?.title ?? "collection"}"`, "success");
              }}
              onOpenSermon={(note) => {
                router.push({ pathname: "/reading-mode", params: { id: note.testimony_id, targetIndex: String(note.paragraph_number - 1) } });
              }}
            />
          ))}
        </ScrollView>
      )}

      <ExportSheet
        visible={showExportSheet}
        collection={collection}
        notes={notes}
        onClose={() => setShowExportSheet(false)}
        toast={toast}
        colors={colors}
        theme={theme}
      />
    </View>
  );
}

// ─────────────────────────────────────────────────────────────
// Passage Card — share icon removed; export is collection-level only
// ─────────────────────────────────────────────────────────────
function PassageCard({
  note, allCollections, colors, theme, onDelete, onMove, onOpenSermon,
}: {
  note: UserNote;
  allCollections: NoteCollection[];
  colors: any;
  theme: string;
  onDelete: (id: string) => void;
  onMove: (id: string, collectionId: string) => void;
  onOpenSermon: (note: UserNote) => void;
}) {
  const styles = getStyles(colors, theme);
  const [personalNote, setPersonalNote] = useState(note.personal_note || "");
  const [savedStatus, setSavedStatus] = useState<"idle" | "saving" | "saved">("idle");
  const [showMoveSheet, setShowMoveSheet] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  const handlePersonalNoteChange = (text: string) => {
    setPersonalNote(text);
    setSavedStatus("saving");
    if (debounceRef.current) clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(async () => {
      await api.updatePersonalNote(note.id, text);
      setSavedStatus("saved");
      setTimeout(() => setSavedStatus("idle"), 2000);
    }, 800);
  };

  const handleDeletePassage = () => {
    Alert.alert("Remove Passage", "Remove this passage from the collection?", [
      { text: "Cancel", style: "cancel" },
      { text: "Remove", style: "destructive", onPress: () => onDelete(note.id) },
    ]);
  };

  return (
    <View style={[styles.passageCard, { borderColor: colors.hairline }]}>
      <Pressable onPress={() => onOpenSermon(note)} style={styles.passageHeaderRow}>
        <View style={{ flex: 1 }}>
          <Text style={styles.passageSermonTitle} numberOfLines={2}>{note.testimony_title || "Sermon"}</Text>
          <Text style={styles.passageMeta}>{[note.date_code, note.speaker, note.language].filter(Boolean).join(" · ")}</Text>
        </View>
        <Ionicons name="open-outline" size={16} color={colors.emerald} style={{ marginLeft: spacing[2] }} />
      </Pressable>

      <Text style={styles.passageParaNum}>Paragraph {note.paragraph_number}</Text>

      <TranscriptParagraphText text={`\u201C${note.text}\u201D`} style={styles.passageQuote} numberOfLines={6} />

      <View style={[styles.divider, { backgroundColor: colors.hairline }]} />

      <View style={styles.myNotesRow}>
        <Text style={styles.myNotesLabel}>My Notes</Text>
        {savedStatus === "saved" && <Text style={styles.savedIndicator}>Saved ✓</Text>}
        {savedStatus === "saving" && <Text style={styles.savedIndicator}>Saving…</Text>}
      </View>
      <TextInput
        multiline
        value={personalNote}
        onChangeText={handlePersonalNoteChange}
        placeholder="Your sermon preparation notes, Scripture references, thoughts…"
        placeholderTextColor={colors.mutedForeground}
        style={[styles.personalNoteInput, { color: colors.foreground, borderColor: colors.hairline }]}
      />

      <View style={styles.passageActionsRow}>
        {allCollections.length > 0 && (
          <Pressable onPress={() => setShowMoveSheet(true)} style={styles.passageActionBtn}>
            <Ionicons name="swap-horizontal-outline" size={14} color={colors.mutedForeground} />
            <Text style={styles.passageActionText}>Move</Text>
          </Pressable>
        )}
        <Pressable onPress={handleDeletePassage} style={styles.passageActionBtn}>
          <Ionicons name="trash-outline" size={14} color={colors.mutedForeground} />
          <Text style={styles.passageActionText}>Remove</Text>
        </Pressable>
      </View>

      {showMoveSheet && (
        <View style={[styles.moveSheet, { backgroundColor: colors.surface, borderColor: colors.hairline }]}>
          <Text style={[styles.myNotesLabel, { marginBottom: spacing[2] }]}>Move to</Text>
          {allCollections.map((col) => (
            <Pressable key={col.id} style={[styles.moveRow, { borderColor: colors.hairline }]} onPress={() => { setShowMoveSheet(false); onMove(note.id, col.id); }}>
              <Ionicons name="folder-outline" size={16} color={colors.emerald} />
              <Text style={[styles.collectionRowText, { color: colors.foreground }]} numberOfLines={1}>{col.title}</Text>
            </Pressable>
          ))}
          <Pressable onPress={() => setShowMoveSheet(false)} style={{ paddingVertical: spacing[2], alignItems: "center" }}>
            <Text style={{ color: colors.mutedForeground, fontFamily: typography.sansSemi, fontSize: 13 }}>Cancel</Text>
          </Pressable>
        </View>
      )}
    </View>
  );
}

// ─────────────────────────────────────────────────────────────
// Styles
// ─────────────────────────────────────────────────────────────
const getStyles = (colors: any, theme: string) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: { flexDirection: "row", alignItems: "center", paddingHorizontal: spacing[4], paddingVertical: spacing[3], borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.hairline },
    backBtn: { padding: spacing[1], marginRight: spacing[2] },
    headerTitle: { flex: 1, fontSize: 18, fontFamily: typography.serif, color: colors.foreground },
    headerBtn: { padding: spacing[2] },
    metaRow: { paddingHorizontal: spacing[5], paddingTop: spacing[3], paddingBottom: spacing[1] },
    metaText: { fontSize: 12, fontFamily: typography.sansSemi, color: colors.mutedForeground, textTransform: "uppercase", letterSpacing: 1.2 },
    loadingText: { color: colors.mutedForeground, textAlign: "center", marginTop: 40, fontFamily: typography.sans },
    emptyWrap: { flex: 1, alignItems: "center", justifyContent: "center", padding: spacing[8] },
    emptyTitle: { fontSize: 18, fontFamily: typography.serif, color: colors.foreground, marginBottom: spacing[2] },
    emptyMessage: { fontSize: 14, fontFamily: typography.sans, color: colors.mutedForeground, textAlign: "center", lineHeight: 22 },
    passageCard: { borderWidth: 1, borderRadius: radii["2xl"], padding: spacing[5], marginBottom: spacing[5] },
    passageHeaderRow: { flexDirection: "row", alignItems: "flex-start", marginBottom: spacing[3] },
    passageSermonTitle: { fontSize: 14, fontFamily: typography.sansSemi, color: colors.foreground },
    passageMeta: { fontSize: 12, fontFamily: typography.sans, color: colors.mutedForeground, marginTop: 2 },
    passageParaNum: { fontSize: 11, fontFamily: typography.sansSemi, color: colors.emerald, letterSpacing: 1.2, textTransform: "uppercase", marginBottom: spacing[2] },
    passageQuote: { color: colors.foreground, lineHeight: 24 },
    divider: { height: StyleSheet.hairlineWidth, marginVertical: spacing[4] },
    myNotesRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: spacing[2] },
    myNotesLabel: { fontSize: 11, fontFamily: typography.sansSemi, color: colors.mutedForeground, textTransform: "uppercase", letterSpacing: 1.2 },
    savedIndicator: { fontSize: 11, fontFamily: typography.sansSemi, color: colors.emerald },
    personalNoteInput: { minHeight: 80, paddingHorizontal: spacing[3], paddingVertical: spacing[3], borderRadius: radii.lg, borderWidth: 1, fontFamily: typography.sans, fontSize: 14, lineHeight: 22, textAlignVertical: "top" },
    passageActionsRow: { flexDirection: "row", gap: spacing[4], marginTop: spacing[3], justifyContent: "flex-end" },
    passageActionBtn: { flexDirection: "row", alignItems: "center", gap: 4 },
    passageActionText: { fontSize: 12, fontFamily: typography.sansSemi, color: colors.mutedForeground },
    moveSheet: { marginTop: spacing[3], borderRadius: radii.xl, borderWidth: 1, padding: spacing[4] },
    moveRow: { flexDirection: "row", alignItems: "center", gap: spacing[3], paddingVertical: spacing[2], borderBottomWidth: StyleSheet.hairlineWidth },
    collectionRowText: { flex: 1, fontSize: 14, fontFamily: typography.sans },
  });
